# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-23 01:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20161122_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AddField(
            model_name='productservicerelationship',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Quantidade'),
        ),
    ]
